#!/bin/bash

repl(){
    clj -A:core:cljc:jvm:repl --init-ns cljctools.bittorrent.bencode.core-test
}

nodejs(){
    yarn install --no-lockfile
    # -i :integration
    # -n cljctools.socket.nodejs-net-test
    clojure -A:core:cljc:js:js-test-runner -x node -d src "$@"
}

jvm(){

    # -i :integration -i :example
    # -v cljctools.socket.java-net-test/core-async-blocking-put-in-catch
    clojure -A:core:cljc:jvm:jvm-test-runner -d src "$@"
}

clean(){
    rm -rf .cpcache node_modules target
}

"$@"